services:
  web-server:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

    #mengaktifkan driver Mysql
    command: >
      sh -c "docker-php-ext-install mysqli pdo pdo_mysql && apache2-foreground"
    depends_on:
      - mysql-db

 #service 2
  mysql-db:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: phpmvc
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:  